CREATE DATABASE IF NOT EXISTS aquaguard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE aquaguard;

CREATE TABLE IF NOT EXISTS menro_accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) DEFAULT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(150) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ranger_accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) DEFAULT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(150) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active TINYINT(1) NOT NULL DEFAULT 1
);

ALTER TABLE menro_accounts ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE ranger_accounts ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE menro_accounts MODIFY COLUMN full_name VARCHAR(100) DEFAULT NULL AFTER id;
ALTER TABLE ranger_accounts MODIFY COLUMN full_name VARCHAR(100) DEFAULT NULL AFTER id;

CREATE TABLE IF NOT EXISTS admin_accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS login_lockouts (
  username VARCHAR(50) NOT NULL PRIMARY KEY,
  failed_attempts INT NOT NULL DEFAULT 0,
  lockout_count INT NOT NULL DEFAULT 0,
  locked_until TIMESTAMP NULL DEFAULT NULL,
  last_attempt_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  actor_username VARCHAR(50) NOT NULL,
  actor_role VARCHAR(20) NOT NULL,
  action VARCHAR(190) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE audit_log MODIFY COLUMN action VARCHAR(190) NOT NULL;

CREATE TABLE IF NOT EXISTS password_reset_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  role VARCHAR(20) DEFAULT NULL,
  account_id INT DEFAULT NULL,
  status ENUM('pending','resolved') NOT NULL DEFAULT 'pending',
  token VARCHAR(64) DEFAULT NULL,
  token_expires_at TIMESTAMP NULL DEFAULT NULL,
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP NULL DEFAULT NULL
);
